# Generated by Django 3.0.2 on 2020-11-08 07:21

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GroupNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, db_column='name', max_length=150)),
                ('comment', models.TextField(blank=True, db_column='comment')),
                ('isActive', models.BooleanField(db_column='isActive', default=True)),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
                'db_table': 'GroupNotification',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, db_column='name', max_length=150)),
                ('isActive', models.BooleanField(db_column='isActive', default=True)),
                ('parent', models.ForeignKey(db_column='parent', null=True, on_delete=django.db.models.deletion.CASCADE, to='SystemNotification.GroupNotification')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
                'db_table': 'Notification',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='NotificationState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, db_column='name', max_length=30, unique=True)),
                ('isActive', models.BooleanField(db_column='isActive', default=True)),
            ],
            options={
                'verbose_name': 'Состояние',
                'verbose_name_plural': 'Состояния задач',
                'db_table': 'NotificationState',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='NotificationHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.DateTimeField(db_column='period', db_index=True, default=datetime.datetime(2020, 11, 8, 10, 21, 34, 6732))),
                ('name', models.CharField(blank=True, db_column='name', max_length=150)),
                ('isActive', models.BooleanField(db_column='isActive', default=True)),
                ('notification', models.ForeignKey(db_column='notification', null=True, on_delete=django.db.models.deletion.CASCADE, to='SystemNotification.Notification')),
                ('state', models.ForeignKey(db_column='state', null=True, on_delete=django.db.models.deletion.PROTECT, to='SystemNotification.NotificationState')),
            ],
            options={
                'verbose_name': 'История',
                'verbose_name_plural': 'Истории изменения',
                'db_table': 'NotificationHistory',
                'ordering': ['-notification', '-period'],
                'unique_together': {('period', 'notification')},
            },
        ),
    ]
