# Generated by Django 3.0.2 on 2020-11-08 07:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SystemNotification', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificationhistory',
            name='name',
        ),
        migrations.AlterField(
            model_name='notificationhistory',
            name='period',
            field=models.DateTimeField(db_column='period', db_index=True, default=datetime.datetime(2020, 11, 8, 10, 28, 9, 560161)),
        ),
    ]
