# Generated by Django 3.0.2 on 2020-11-08 07:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SystemNotification', '0002_auto_20201108_1028'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-id'], 'verbose_name': 'Подзадача', 'verbose_name_plural': 'Подзадачи'},
        ),
        migrations.AlterField(
            model_name='notificationhistory',
            name='period',
            field=models.DateTimeField(db_column='period', db_index=True, default=datetime.datetime(2020, 11, 8, 10, 30, 3, 186180)),
        ),
    ]
