# Generated by Django 3.0.2 on 2020-11-08 07:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SystemNotification', '0003_auto_20201108_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationhistory',
            name='period',
            field=models.DateTimeField(db_column='period', db_index=True, default=datetime.datetime(2020, 11, 8, 10, 34, 24, 960702)),
        ),
    ]
