# Generated by Django 3.0.2 on 2020-11-08 07:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SystemNotification', '0004_auto_20201108_1034'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-parent', '-id'], 'verbose_name': 'Подзадача', 'verbose_name_plural': 'Подзадачи'},
        ),
        migrations.AlterField(
            model_name='notificationhistory',
            name='period',
            field=models.DateTimeField(db_column='period', db_index=True, default=datetime.datetime(2020, 11, 8, 10, 35, 1, 558193)),
        ),
    ]
