# Generated by Django 3.0.2 on 2020-11-08 07:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SystemNotification', '0007_auto_20201108_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationhistory',
            name='period',
            field=models.DateTimeField(db_column='period', db_index=True, default=datetime.datetime(2020, 11, 8, 10, 43, 40, 655724)),
        ),
    ]
