# Generated by Django 3.0.2 on 2020-11-08 08:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SystemNotification', '0008_auto_20201108_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationhistory',
            name='period',
            field=models.DateTimeField(db_column='period', db_index=True, default=datetime.datetime(2020, 11, 8, 11, 10, 17, 922584)),
        ),
    ]
