# Generated by Django 3.0.2 on 2020-11-08 09:16

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SystemNotification', '0010_auto_20201108_1111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificationhistory',
            name='isActive',
        ),
        migrations.AddField(
            model_name='notification',
            name='period',
            field=models.DateTimeField(db_column='period', db_index=True, default=datetime.datetime(2020, 11, 8, 12, 16, 9, 381403)),
        ),
        migrations.AddField(
            model_name='notification',
            name='state',
            field=models.ForeignKey(db_column='state', null=True, on_delete=django.db.models.deletion.PROTECT, to='SystemNotification.NotificationState'),
        ),
        migrations.AlterField(
            model_name='notificationhistory',
            name='period',
            field=models.DateTimeField(db_column='period', db_index=True, default=datetime.datetime(2020, 11, 8, 12, 16, 9, 382403)),
        ),
    ]
