# Generated by Django 3.0.2 on 2020-11-08 09:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SystemNotification', '0012_auto_20201108_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='period',
            field=models.DateTimeField(db_column='period', db_index=True, default=datetime.datetime(2020, 11, 8, 12, 24, 26, 45188)),
        ),
        migrations.AlterField(
            model_name='notificationhistory',
            name='period',
            field=models.DateTimeField(db_column='period', db_index=True, default=datetime.datetime(2020, 11, 8, 12, 24, 26, 45188)),
        ),
    ]
