# Generated by Django 3.0.2 on 2020-11-08 09:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SystemNotification', '0013_auto_20201108_1224'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupnotification',
            options={'ordering': ['-id'], 'verbose_name': 'Группа задач', 'verbose_name_plural': 'Группы задач'},
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['parent', '-id'], 'verbose_name': 'Задача', 'verbose_name_plural': 'Задачи'},
        ),
        migrations.AlterField(
            model_name='notification',
            name='period',
            field=models.DateTimeField(db_column='period', db_index=True, default=datetime.datetime(2020, 11, 8, 12, 32, 32, 73886)),
        ),
        migrations.AlterField(
            model_name='notificationhistory',
            name='period',
            field=models.DateTimeField(db_column='period', db_index=True, default=datetime.datetime(2020, 11, 8, 12, 32, 32, 73886)),
        ),
    ]
