# Generated by Django 3.0.2 on 2020-11-08 09:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SystemNotification', '0016_auto_20201108_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='period',
            field=models.DateTimeField(db_column='period', db_index=True, default=datetime.datetime(2020, 11, 8, 12, 54, 52, 933985)),
        ),
        migrations.AlterField(
            model_name='notificationhistory',
            name='period',
            field=models.DateTimeField(db_column='period', db_index=True, default=datetime.datetime(2020, 11, 8, 12, 54, 52, 934984)),
        ),
    ]
