# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-11-09 13:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SystemNotification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationstate',
            name='back_blue',
            field=models.IntegerField(db_column=b'back_blue', default=255),
        ),
        migrations.AddField(
            model_name='notificationstate',
            name='back_green',
            field=models.IntegerField(db_column=b'back_green', default=255),
        ),
        migrations.AddField(
            model_name='notificationstate',
            name='back_red',
            field=models.IntegerField(db_column=b'back_red', default=255),
        ),
        migrations.AddField(
            model_name='notificationstate',
            name='blue',
            field=models.IntegerField(db_column=b'blue', default=0),
        ),
        migrations.AddField(
            model_name='notificationstate',
            name='green',
            field=models.IntegerField(db_column=b'green', default=0),
        ),
        migrations.AddField(
            model_name='notificationstate',
            name='red',
            field=models.IntegerField(db_column=b'red', default=0),
        ),
        migrations.AlterField(
            model_name='notification',
            name='period',
            field=models.DateTimeField(blank=True, db_column=b'period', db_index=True, default=datetime.datetime(2020, 11, 9, 13, 14, 49, 528709)),
        ),
        migrations.AlterField(
            model_name='notificationhistory',
            name='period',
            field=models.DateTimeField(blank=True, db_column=b'period', db_index=True, default=datetime.datetime(2020, 11, 9, 13, 14, 49, 529183)),
        ),
    ]
