# Generated by Django 3.1.3 on 2020-12-01 12:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SystemNotification', '0002_auto_20201201_0835'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='comment',
            field=models.TextField(blank=True, db_column='comment'),
        ),
        migrations.AlterField(
            model_name='historysubnotificationcomments',
            name='period',
            field=models.DateTimeField(blank=True, db_column='period', db_index=True, default=datetime.datetime(2020, 12, 1, 12, 55, 59, 631491)),
        ),
        migrations.AlterField(
            model_name='notification',
            name='period',
            field=models.DateTimeField(blank=True, db_column='period', db_index=True, default=datetime.datetime(2020, 12, 1, 12, 55, 59, 631491)),
        ),
        migrations.AlterField(
            model_name='notificationhistory',
            name='period',
            field=models.DateTimeField(blank=True, db_column='period', db_index=True, default=datetime.datetime(2020, 12, 1, 12, 55, 59, 632491)),
        ),
        migrations.AlterField(
            model_name='subnotificationcomments',
            name='period',
            field=models.DateTimeField(blank=True, db_column='period', db_index=True, default=datetime.datetime(2020, 12, 1, 12, 55, 59, 631491)),
        ),
    ]
